site_url: https://openatlas-discovery-demo.acdh-ch-dev.oeaw.ac.at
logo_url: /icon.svg
load_config_file: true
local_backend: true
backend:
  name: github
  repo: acdh-oeaw/openatlas-discovery
  branch: develop
  base_url: https://openatlas-discovery-demo.acdh-ch-dev.oeaw.ac.at
  auth_endpoint: /api/oauth/authorize
  auth_scope: repo
  squash_merges: true
  commit_messages:
    create: "content(create): {{collection}} '{{slug}}'"
    update: "content(update): {{collection}} '{{slug}}'"
    delete: "content(delete): {{collection}} '{{slug}}'"
    uploadMedia: "content(upload): '{{path}}'"
    deleteMedia: "content(delete): '{{path}}'"
# publish_mode: editorial_workflow
media_folder: /public/assets/images
public_folder: /assets/images
editor:
  preview: false
i18n:
  structure: multiple_folders
  locales:
    - en
    - de
  default_locale: en
collections:
  - name: config
    label: Config
    # description: Config
    files:
      - name: project_config
        label: Project config
        file: project.config.json
        fields:
          - name: colors
            label: Colors
            # hint: Colors
            widget: object
            fields:
              - name: brand
                label: Brand
                # hint: Brand color
                widget: color
                allowInput: true

              - name: geojsonPoints
                label: GeoJSON Location Points
                # hint: GeoJSON points color
                widget: color
                allowInput: true

              - name: geojsonAreaCenterPoints
                label: GeoJSON Areas and their Centers
                # hint: GeoJSON areas color
                widget: color
                allowInput: true

              - name: geojsonMovement
                label: GeoJSON Movement Points
                # hint: GeoJSON areas color
                widget: color
                allowInput: true

          - name: defaultLocale
            label: Default locale
            # hint: Default locale
            widget: select
            options:
              - value: en
                label: English
              - value: de
                label: German

          - name: fullscreen
            label: Make the Website's Data Visualization Fullscreen per Default
            # hint: Make the Website's Data Visualization Fullscreen per Default
            widget: boolean
            default: false

          - name: map
            label: Map Configuration
            # hint: Map Configuration
            widget: object
            fields:
              - name: startPage
                label: Make the Map the Start Page of the Website
                # hint: Make the Map the Start Page of the Website
                widget: boolean
                default: false

              - name: mapDisplayedSystemClasses
                label: Configure which system classes with coordinates are displayed on the map
                # hint: Consider which are relevant for your research, the more you select, the map will take longer to load
                widget: select
                multiple: true
                options:
                  [
                    "place",
                    "feature",
                    "move",
                    "statigraphic_unit",
                    "artifact",
                    "person",
                    "group",
                    "event",
                    "acquisition",
                    "human_remains",
                    "activity",
                  ]
                default: ["place"]

          - name: network
            label: Network Configuration
            # hint: Network Configuration
            widget: object
            fields:
              - name: excludeSystemClasses
                label: Configure which system classes should be excluded from the network
                # hint: Configure which system classes are not displayed in the network
                widget: select
                multiple: true
                options:
                  [
                    "place",
                    "feature",
                    "move",
                    "statigraphic_unit",
                    "artifact",
                    "appellation",
                    "creation",
                    "production",
                    "person",
                    "group",
                    "event",
                    "acquisition",
                    "human_remains",
                    "activity",
                    "type",
                    "reference_system",
                    "file",
                    "source_translation",
                    "source",
                    "bibliography",
                    "external_reference",
                    "administrative_unit",
                    "edition",
                    "type_tools",
                  ]
                default:
                  [
                    "type",
                    "reference_system",
                    "file",
                    "source_translation",
                    "source",
                    "bibliography",
                    "external_reference",
                    "administrative_unit",
                    "edition",
                    "type_tools",
                  ]

          - name: imprint
            label: Imprint
            # hint: Imprint page
            widget: select
            options:
              - value: none
                label: No imprint
              - value: custom
                label: Use custom imprint page
              - value: acdh-ch
                label: Use ACDH-CH imprint

          - name: twitter
            label: Twitter
            # hint: Twitter handle
            required: false

  - name: metadata
    label: Metadata
    # description: Metadata
    i18n: true
    # currently file collections only support the "single_file" i18n structure,
    # so we create a folder collection with a single entry, and disallow creating
    # new entries.
    folder: messages
    identifier_field: __cms__
    format: json
    create: false
    delete: false
    summary: Project metadata
    filter:
      field: __cms__
      value: true
    fields:
      - name: __cms__
        widget: hidden

      - name: Metadata
        label: Metadata
        i18n: true
        # hint: Metadata
        widget: object
        fields:
          - name: name
            label: Title
            i18n: true
            # hint: The website title

          - name: shortName
            label: Short title
            i18n: true
            # hint: The website short title

          - name: description
            label: Description
            i18n: true
            # hint: The website description
            widget: text

  - name: systemPages
    label: System pages
    label_singular: System page
    # description: System pages
    i18n: true
    folder: content/system-pages
    create: false
    delete: false
    fields:
      - name: title
        label: Title
        i18n: true
        # hint: The title

      - name: navigation
        label: Navigation
        i18n: true
        # hint: The navigation
        widget: object
        fields:
          - name: title
            label: Title
            i18n: true
            # hint: The navigation title

      - name: image
        label: Hero image
        i18n: true
        # hint: Hero image
        widget: object
        required: false
        fields:
          - name: light
            label: Hero image (light mode)
            i18n: true
            # hint: Hero image (light mode)
            widget: image

          - name: dark
            label: Hero image (dark mode)
            i18n: true
            # hint: Hero image (dark mode)
            widget: image

      - name: leadIn
        label: Hero lead-in
        i18n: true
        # hint: Hero lead-in
        widget: markdown
        modes:
          # - raw
          - rich_text

      - name: links
        label: Links
        i18n: true
        hint: Call to action links
        widget: list
        required: false
        fields:
          - name: label
            label: label
            i18n: true
            # hint: The link label

          - name: href
            label: URL
            i18n: duplicate
            hint: The pathname, e.g. "/about"

      - name: body
        label: Content
        i18n: true
        # hint: The content
        widget: markdown
        modes:
          # - raw
          - rich_text

  - name: pages
    label: Pages
    label_singular: Page
    # description: Pages
    i18n: true
    folder: content/pages
    create: true
    delete: true
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        i18n: true
        # hint: The title

      - name: navigation
        label: Navigation
        i18n: true
        # hint: The navigation
        widget: object
        fields:
          - name: title
            label: Title
            i18n: true
            # hint: The navigation title

      - name: body
        label: Content
        i18n: true
        # hint: The content
        widget: markdown
        modes:
          # - raw
          - rich_text

  - name: team
    label: Team
    label_singular: Team member
    # description: Team
    i18n: true
    folder: content/team
    media_folder: /public/assets/images/team
    public_folder: /assets/images/team
    identifier_field: lastName
    create: true
    delete: true
    slug: "{{lastName}}-{{firstName}}"
    summary: "{{firstName}} {{lastName}}"
    fields:
      - name: firstName
        label: First name
        i18n: duplicate
        # hint: The first name
        required: false

      - name: lastName
        label: Last name
        i18n: duplicate
        # hint: The last name

      - name: academicTitle
        label: Title
        i18n: duplicate
        # hint: The academic title
        required: false

      - name: image
        label: Image
        i18n: duplicate
        # hint: The image
        widget: image
        required: false

      - name: body
        label: Short biography
        i18n: true
        # hint: The short biography
        widget: markdown
        modes:
          # - raw
          - rich_text
